language: rust

matrix:
  include:
    - rust: nightly
      script:
        - cargo build
        - cargo build --manifest-path tests/deps/Cargo.toml
        - cargo test
        - cargo test --features preserve_order
        - cargo test --features arbitrary_precision
        - cargo test --features raw_value
        - cargo test --features unbounded_depth

    - rust: 1.15.0
      script:
        # preserve_order is not supported on 1.15.0
        - cargo build
        - cargo build --features arbitrary_precision

    - rust: stable
    - rust: beta
    - rust: 1.18.0

    - rust: nightly
      name: Clippy
      script:
        - rustup component add clippy || travis_terminate 0
        - cargo clippy

script:
  - cargo build
  - cargo build --features preserve_order
  - cargo build --features arbitrary_precision
